---
- name: Add users to a Cisco device
  hosts: all
  vars:
    users_config: "./ios_config/users.cfg"
  tasks:
    name: "Push config file to IOS device"
    cisco.ios.ios_config:
      src: "{{ users_config }}"

    name: Save running config to startup when modified.
    cisco.ios.ios_config:
      save_when: modified


