---
- name: Add users to a Cisco device
  hosts: all
  gather_facts: no
  vars:
    users_config: "ios_config/users.cfg"
  tasks:
    - name: "Push config file to IOS device"
      cisco.ios.ios_config:
        src: "{{ users_config }}"

    - name: save running to startup when modified
      ios_config:
        save_when: modified
