---
- name: Add users to a Cisco device
  hosts: all
  gather_facts: no

  vars:
    repo_url: "https://{{git_user|urlencode()}}:{{git_pass|urlencode()}}@github.com/my0373/ios_backups.git"
    tmp_repo_directory:  "/tmpgit"

  tasks:
    - name: Clone GIT Repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ tmp_repo_directory }}"
        clone: yes
        update: yes

    - name: Configure local git
      git_config:
        name: user.email
        scope: global
        value: 'my0373@gmail.com'

    - name: "Write backup to disk"
      ansible.builtin.copy:
        content:  "Timmy" 
        dest: "{{ tmp_repo_directory }}/{{ inventory_hostname }}-backup.cfg"

    - name: Add new files
      ansible.builtin.command: git add .
      args:
        chdir: "{{ tmp_repo_directory }}"

    - name: Commit
      ansible.builtin.command: git commit -am "test"
      args:
        chdir: "{{ tmp_repo_directory }}"

    - name: Push
      ansible.builtin.command: git push
      args:
        chdir: "{{ tmp_repo_directory }}"
#
#    - name: "Copy backup to router"
#      cisco.ios.ios_config:
#        src: "/{{ inventory_hostname }}-backup.cfg"
#
#    - name: save running to startup
#      cisco.ios.ios_config:
#        save_when: modified


