---
- name: Add users to a Cisco device
  hosts: all
  gather_facts: no

  vars:
    repo_url: "https://{{git_user|urlencode()}}:{{git_pass|urlencode()}}@github.com/my0373/ios_backups.git"
    tmp_repo_directory:  "/tmpgit"

  tasks:
    - name: Clone GIT Repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ tmp_repo_directory }}"
        clone: yes
        update: yes

    ## Th next few lines ignore errors. This is just for testing.
    - name: Checkout new branch
      ansible.builtin.command: git checkout "{{ safe_hash }}"
      args:
        chdir: "{{ tmp_repo_directory }}"

    - name: Configure git username
      ansible.builtin.command: git config --global user.name "Matt York"
      args:
        chdir: "{{ tmp_repo_directory }}"

    - name: Configure git email
      ansible.builtin.command: git config --global user.email my0373@gmail.com
      args:
        chdir: "{{ tmp_repo_directory }}"

    - name: "Restore Cisco IOS Device backup {{ inventory_hostname }} #{{ safe_hash }}"
      cisco.ios.ios_config:
        src: "{{ tmp_repo_directory }}/{{ inventory_hostname }}-backup.cfg"

    - name: Save running to startup
      cisco.ios.ios_config:
        save_when: modified

    ## Th next few lines ignore errors. This is just for testing.
    - name: Add new files
      ansible.builtin.command: git add .
      args:
        chdir: "{{ tmp_repo_directory }}"
      ignore_errors: yes

#    - name: "Copy backup to router"
#      cisco.ios.ios_config:
#        src: "/{{ inventory_hostname }}-backup.cfg"
#
#    - name: save running to startup
#      cisco.ios.ios_config:
#        save_when: modified


