---
  - name: "Backup a Cisco IOS device"
    hosts: all
    tasks:
    - name: "Backup Cisco IOS Device {{ inventory_hostname }}"
      cisco.ios.ios_config:
        backup: yes
      register: backup_output

    - name: "Load backup into a workflow variable"
      ansible.builtin.set_stats:
        aggregate: no
        data:
          backup_contents: "{{ lookup('file',  backup_output['backup_path']) }}"

