---
- name: snmp ro/rw string configuration
  hosts: all
  gather_facts: no

  tasks:
  - name: ensure that the desired snmp strings are present
    cisco.ios.config:
      commands:
      - snmp-server community {{ snmp_string }} {{ string_type }}
  
