---
- name: "Collect facts from a Cisco IOS device"
  hosts: all
  tasks:
    - name: "Run the collection on host {{ inventory_hostname }}"
      cisco.ios.ios_facts:
        gather_subset: all
      register: ios_rtr_facts

    - name: "Print the discovered facts to the screen"
      ansible.builtin.debug:
        var: ios_rtr_facts
        
